import {Metadata} from "next"

export const metadata: Metadata = {
  title: {
    default:"next.js tutorial",
    template:"%s codevalution",
    absolute: "",
  },
  description:"generated by next.js"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}>
            <p>header</p>
        </header>
        {children}
        <footer style={{
          backgroundColor: "ghostwhite",
          padding:"1rem"
        }}>
          <p>footer</p>
        </footer>
        </body>
    </html>
  );
}
